# Generated by Django 4.2.25 on 2025-10-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='parent_story_entry',
        ),
        migrations.RemoveField(
            model_name='storyentry',
            name='author',
        ),
        migrations.AddField(
            model_name='storyentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
        migrations.AddField(
            model_name='storyentry',
            name='node',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
