# Generated by Django 4.2.25 on 2025-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_storyentry_ai_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyentry',
            name='context',
            field=models.TextField(default=''),
        ),
    ]
